CREATE TABLE Person (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	email varchar NOT NULL,
	password varchar NOT NULL
);

CREATE TABLE Task(
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	title varchar NOT NULL,
	description varchar,
	status varchar NOT NULL,
	priority varchar NOT NULL,
	author_id int NOT NULL,
	executor_id int
);

CREATE TABLE Comment(
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	task_id int NOT NULL,
	author_id int NOT NULL,
	text varchar NOT NULL
);